"""Initial migration

Revision ID: 248926056128
Revises: 
Create Date: 2026-06-07 15:44:04.751269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248926056128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('points', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_name', sa.String(length=50), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('lesson_name')
    )
    op.create_table('students',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('homeworks',
    sa.Column('homework_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('homework_name', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('homework_id'),
    sa.UniqueConstraint('homework_name')
    )
    op.create_table('homework_tasks',
    sa.Column('homework_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.homework_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('homework_id', 'task_id')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.BigInteger(), nullable=False),
    sa.Column('homework_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.homework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('homework_tasks')
    op.drop_table('homeworks')
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('lessons')
    op.drop_table('enrollments')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('courses')
    # ### end Alembic commands ###
